-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 10:58:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jornadaABGG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jornadaABGG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jornadaABGG` DEFAULT CHARACTER SET utf8 ;
USE `jornadaABGG` ;

-- -----------------------------------------------------
-- Table `jornadaABGG`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jornadaABGG`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jornadaABGG`.`inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jornadaABGG`.`inscritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `sexo` VARCHAR(2) NULL,
  `data_cadastro` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jornadaABGG`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `jornadaABGG`;
INSERT INTO `jornadaABGG`.`login` (`id`, `user`, `senha`) VALUES (1, 'admin', '04e1f21b23e32381051edbe190aac2a7');

COMMIT;

